"""
PPT Engine - Spec Lock生成器

生成spec_lock.md文件，作为SVG生成的执行契约。
"""

from pathlib import Path
from typing import Dict, List, Any, Optional
from datetime import datetime

from .strategist import DesignSpec


class SpecLockGenerator:
    """Spec Lock生成器"""

    def __init__(self, project_path: str):
        """
        初始化生成器

        参数:
            project_path: 项目路径
        """
        self.project_path = Path(project_path)

    def generate(self, spec: DesignSpec) -> str:
        """
        生成spec_lock.md内容

        参数:
            spec: 设计规范

        返回:
            Markdown内容
        """
        # 生成页面列表
        pages_section = self._generate_pages_section(spec)

        # 生成颜色锁定
        colors_section = self._generate_colors_section(spec)

        # 生成字体锁定
        typography_section = self._generate_typography_section(spec)

        # 生成图片资源列表
        images_section = self._generate_images_section(spec)

        md = f"""# Spec Lock - {spec.title}

> **WARNING**: This file is machine-readable execution contract.
> Executor MUST re-read this file before generating each SVG page.
> All colors, fonts, icons, images MUST come from this file.

## Canvas

- format: {spec.canvas_format}
- width: {spec.width}
- height: {spec.height}

{colors_section}

{typography_section}

## Icon Style

- style: {spec.icon_style}
- library: {spec.icon_library}

{images_section}

{pages_section}

## Animation

- transition: fade
- entrance: auto
- trigger: after-previous

## Quality Rules

- viewBox: required
- group_ids: required
- banned_features: xlink:href, script, foreignObject

---
*Generated by PPT Engine SpecLockGenerator at {datetime.now().isoformat()}*
"""
        return md

    def _generate_colors_section(self, spec: DesignSpec) -> str:
        """生成颜色部分"""
        return f"""## Colors

| Role | Value |
|------|-------|
| primary | {spec.colors.primary} |
| secondary | {spec.colors.secondary} |
| accent | {spec.colors.accent} |
| background | {spec.colors.background} |
| surface | {spec.colors.surface} |
| text | {spec.colors.text} |
| text_secondary | {spec.colors.text_secondary} |"""

    def _generate_typography_section(self, spec: DesignSpec) -> str:
        """生成字体部分"""
        return f"""## Typography

| Role | Font | Size |
|------|------|------|
| title | {spec.typography.title_font} | {spec.typography.title_size}px |
| subtitle | {spec.typography.title_font} | {spec.typography.subtitle_size}px |
| body | {spec.typography.body_font} | {spec.typography.body_size}px |
| caption | {spec.typography.body_font} | {spec.typography.caption_size}px |

- formula_policy: {spec.formula_policy}"""

    def _generate_images_section(self, spec: DesignSpec) -> str:
        """生成图片部分"""
        return f"""## Images

- style: {spec.image_style}
- acquisition: {spec.image_acquisition}

| Filename | Acquire Via | Status |
|----------|-------------|--------|"""

    def _generate_pages_section(self, spec: DesignSpec) -> str:
        """生成页面列表部分"""
        if not spec.pages:
            return """## Pages

| # | Title | Layout | Rhythm |
|---|-------|--------|--------|
| 1 | Cover | cover | anchor |
| 2 | Content | content | dense |
| 3 | Ending | ending | breathing |"""

        lines = ["## Pages", "", "| # | Title | Layout | Rhythm |", "|---|-------|--------|--------|"]

        for i, page in enumerate(spec.pages, 1):
            title = page.get('title', f'Page {i}')
            layout = page.get('layout', 'content')
            rhythm = page.get('rhythm', 'dense')
            lines.append(f"| {i} | {title} | {layout} | {rhythm} |")

        return '\n'.join(lines)

    def save(self, spec: DesignSpec) -> Path:
        """
        保存spec_lock.md

        参数:
            spec: 设计规范

        返回:
            保存路径
        """
        content = self.generate(spec)
        output_path = self.project_path / 'spec_lock.md'
        output_path.write_text(content, encoding='utf-8')

        print(f"[OK] Spec lock saved: {output_path}")
        return output_path


def generate_spec_lock(project_path: str, spec: DesignSpec) -> Path:
    """
    生成spec_lock.md（便捷函数）

    参数:
        project_path: 项目路径
        spec: 设计规范

    返回:
        保存路径
    """
    generator = SpecLockGenerator(project_path)
    return generator.save(spec)
